### ISSUE TITLE
problems found to DarkSystem.

### ISSUE THREAD

**Issue by flayzer** [DarkSystem-PE/DarkSystem#24] opened 2017-10-31 04:03 UTC
Errors found:

You can not break down block version 1.2(When you break any block).
On version 1.2, you attract to earth(when you are going to go).

**Comment by Amirgta1** [comment] 2017-10-31 10:26
New problems:
1-Blocking problem in 1.2
2-Commands problem in 1.1 and 1.2
3. Problem walking in 1.2

**Comment by DarkYusuf13** [comment] 2017-11-01 17:41
Thanks for bugs, movement bug is only with 32bit machines and android. Commands will be fixed by adding custom overloads (and commands.json is already removed). Block breaking is caused by PlayerPermissions and AdventureSettingsPacket.
NOTE: I am searching developers for Darksystem, If you want to be, send some pull requests. After I will add you.

**Comment by Amirgta1** [comment] 2017-11-02 06:34
In 1.1, Command Plugins can not be used

**Comment by DarkYusuf13** [comment] 2017-11-02 16:48
@Amirgta1 Okay

**Comment by Amirgta1** [comment] 2017-11-08 17:39
I found a new problem and did not fly in 1.1

**Comment by Amirgta1** [comment] 2017-12-01 18:37
These problems are solved, you can close this issues

**Closed** 2017-12-03 15:31 UTC
Labels: bug
