### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by ghost** [DarkSystem-PE/DarkSystem#59] opened 2017-11-25 20:14 UTC
![Imgur](https://i.imgur.com/6lkQrXL.png)

**Comment by dirouc** [comment] 2017-11-25 20:15
it loop

**Comment by dirouc** [comment] 2017-11-25 20:21
`<20:19:56> DarkSystem 》 CRITICAL: Error: "Call to a member function addEntity() on null" (EXCEPTION) in "/src/pocketmine/entity/Entity" at line 398
<20:19:56> DarkSystem 》 EMERGENCY: Произошла фатальная ошибка и сервер вышел из строя. Создание аварийного дампа
<20:19:56> DarkSystem 》 EMERGENCY: Пожалуйста, загрузите файл"C:\Users\dirouc\Desktop\DarkSystem\crashdumps/CrashDump_Sat_Nov_25-20.19.56-UTC_2017.log" в краш-архив и отправьте ссылку на страницу исправления ошибок. Дайте как можно больше информации.
`
crashdump
`DarkSystem Crash Report Sat Nov 25 20:19:56 UTC 2017

Error: Call to a member function addEntity() on null
File: /src/pocketmine/entity/Entity
Line: 398
Type: notice

Code:
[389] 
[390] 		$this->attributeMap = new AttributeMap();
[391] 		
[392] 		if($this->server->isSupportProtocol("120")){
[393] 			//$this->setDataFlag(Entity::DATA_FLAGS, Entity::DATA_FLAG_AFFECTED_BY_GRAVITY, true);
[394] 			//$this->setDataFlag(Entity::DATA_FLAGS, Entity::DATA_FLAG_HAS_COLLISION, true);
[395] 		}
[396] 		
[397] 		try{ //Bad method
[398] 			$this->chunk->addEntity($this);
[399] 		}catch(\Exception $e){
[400] 			$this->server->getLogger()->emergency("There was an error about current world. Please control your world of server and again.");
[401] 			$this->server->getLogger()->critical("If still not fixed, please contant our developers about problem.");
[402] 		}
[403] 		
[404] 		$level->addEntity($this);
[405] 		$this->initEntity();
[406] 		$this->lastUpdate = $this->server->getTick();
[407] 		$this->server->getPluginManager()->callEvent(new EntitySpawnEvent($this));`

**Comment by dirouc** [comment] 2017-11-25 20:25
I want to use this core in a large project, but so far it's raw

**Comment by DarkYusuf13** [comment] 2017-11-26 08:45
Void world will be fixed, second;
Caused by world, use another world

**Comment by DarkYusuf13** [comment] 2017-11-26 08:46
And is 'auto-generate' = 'on' in server.properties? If not, set it as 'on'.

**Comment by dirouc** [comment] 2017-11-26 09:40
@DarkYusuf13 yes, param is 'on'

**Comment by nikoskon2003** [comment] 2017-11-26 19:13
this is caused because when you die you will have to tap 5 times the respawn button. If you fall int the void you are pressing respawn so you will lower to 4 times, BUT when you 'respawn' the void kills you, so from 4 times it is getting back to 5 times! If you wanna to respawn (well kinda) you can do 2 things! A) delete you player file from /players/(the gametag).dat or B)From the console tp yourself (while in-game) to the spawn (if your spawn is at 0 10 0 do 'tp (gametag) 0 10 0)

**Comment by Yexeed** [comment] 2017-12-02 16:59
How is he launched darksystem under windows? Whem i'm launching the logger doesnt send colors or something like this, as i think. But on linux it works perfect

**Comment by nikoskon2003** [comment] 2017-12-03 15:28
Fixed, will be merged soon!

**Closed by nikoskon2003** 2017-12-03 15:28 UTC
Labels: solving it
